# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: '03-mvc/RestaurantReviews'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(solutionPath)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test --configuration $(buildConfiguration)
  workingDirectory: $(solutionPath)
  displayName: 'dotnet test $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(solutionPath)/RestaurantReviews.WebUI/*.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(0518cd5b-d389-4983-9496-cdcae31dcc60)'
    appType: 'webApp'
    WebAppName: '1904-rest-reviews'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
