//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoapConsumer.UnitConversionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Temperature", Namespace="http://schemas.datacontract.org/2004/07/MySoapService")]
    [System.SerializableAttribute()]
    public partial class Temperature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySoapConsumer.UnitConversionService.Temperature.TempUnit UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySoapConsumer.UnitConversionService.Temperature.TempUnit Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((this.UnitField.Equals(value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Temperature.TempUnit", Namespace="http://schemas.datacontract.org/2004/07/MySoapService")]
        public enum TempUnit : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Fahrenheit = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Celsius = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnitConversionService.IUnitConversionService")]
    public interface IUnitConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/FeetToMeters", ReplyAction="http://tempuri.org/IUnitConversionService/FeetToMetersResponse")]
        double FeetToMeters(double feet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/FeetToMeters", ReplyAction="http://tempuri.org/IUnitConversionService/FeetToMetersResponse")]
        System.Threading.Tasks.Task<double> FeetToMetersAsync(double feet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/ConvertTemperature", ReplyAction="http://tempuri.org/IUnitConversionService/ConvertTemperatureResponse")]
        MySoapConsumer.UnitConversionService.Temperature ConvertTemperature(MySoapConsumer.UnitConversionService.Temperature temperature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/ConvertTemperature", ReplyAction="http://tempuri.org/IUnitConversionService/ConvertTemperatureResponse")]
        System.Threading.Tasks.Task<MySoapConsumer.UnitConversionService.Temperature> ConvertTemperatureAsync(MySoapConsumer.UnitConversionService.Temperature temperature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnitConversionServiceChannel : MySoapConsumer.UnitConversionService.IUnitConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnitConversionServiceClient : System.ServiceModel.ClientBase<MySoapConsumer.UnitConversionService.IUnitConversionService>, MySoapConsumer.UnitConversionService.IUnitConversionService {
        
        public UnitConversionServiceClient() {
        }
        
        public UnitConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnitConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnitConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnitConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FeetToMeters(double feet) {
            return base.Channel.FeetToMeters(feet);
        }
        
        public System.Threading.Tasks.Task<double> FeetToMetersAsync(double feet) {
            return base.Channel.FeetToMetersAsync(feet);
        }
        
        public MySoapConsumer.UnitConversionService.Temperature ConvertTemperature(MySoapConsumer.UnitConversionService.Temperature temperature) {
            return base.Channel.ConvertTemperature(temperature);
        }
        
        public System.Threading.Tasks.Task<MySoapConsumer.UnitConversionService.Temperature> ConvertTemperatureAsync(MySoapConsumer.UnitConversionService.Temperature temperature) {
            return base.Channel.ConvertTemperatureAsync(temperature);
        }
    }
}
