trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '03-mvc/RestaurantReviews'

pool: Default

variables:
  buildConfiguration: 'Release'
  solutionPath: '03-mvc/RestaurantReviews'

steps:

- script: dotnet restore
  workingDirectory: $(solutionPath)
  displayName: 'dotnet restore'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-escalonn'
    organization: 'escalonn-github'
    scannerMode: 'MSBuild'
    projectKey: 'escalona1904restreviews'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportsPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"
  displayName: 'Prepare SonarCloud analysis'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  workingDirectory: $(solutionPath)
  displayName: 'dotnet build'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput='$(Build.ArtifactStagingDirectory)/coverage/'
    /p:Exclude="[xunit*]*"
  workingDirectory: $(solutionPath)
  displayName: 'dotnet test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(Build.ArtifactStagingDirectory)/test'
  displayName: 'Publish test results'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarCloud quality gate result'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(solutionPath)/RestaurantReviews.WebUI/*.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
  displayName: 'dotnet publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
